### ISSUE TITLE
scons: *** Found dependency cycle(s): 

### ISSUE THREAD

**Issue by qindan2008** [egaffo/CirComPara#3]
Hi, egaffo:
When I run Circompara, an error occured like this:
**scons: *** Found dependency cycle(s):**
**File "*/CirComPara-circompara/tools/scons/scons-local-2.5.0/SCons/Taskmaster.py", line 1043, in cleanup.**
How can I fixed this problem ?
Thank you very much !

**Comment by egaffo** [comment]
It could be your meta or vars.py files are not well formatted. Try to include one sample at time in meta rows, also running CirComPara in dry mode (-n option) not to execute the program, and see if and which line cause the error to occur.

**Comment by tigerxu** [comment]
Hi egaffo, I found a same issue with qindan2008 when I configured the vars.py. 

The vars.py I used
META            = "meta.csv"
GENOME_FASTA    = '/data5/haozhang/install/refGenome/mouse/GRCm38.primary_assembly.genome.fa'
ANNOTATION      = '/data5/haozhang/install/refGenome/mouse/star/gencode.vM14.annotation.gtf' 
CIRI            = "/data5/haozhang/install/CirComPara/bin/CIRI_v2.0.2.pl" 
CPUS            = "16"
PREPROCESSOR    = "trimmomatic"
CIRCRNA_METHODS = "circexplorer,findcirc"
TOGGLE_TRANSCRIPTOME_RECONSTRUCTION = 'False'
DIFF_EXP = 'True'
DESEQ = 'True'
PREPROCESSOR_PARAMS = "MAXINFO:40:0.5 LEADING:20 TRAILING:20 SLIDINGWINDOW:4:20 MINLEN:35 AVGQUAL:30"
GENOME_INDEX = '/data5/haozhang/install/refGenome/mouse/hisat2/GRCm38.primary_assembly.genome'
STAR_INDEX = '/data5/haozhang/install/refGenome/mouse/star/'
BOWTIE2_INDEX = '/data5/haozhang/install/refGenome/mouse/bowtie2/GRCm38.primary_assembly.genome'
CUFFNORM_EXTRA_PARAMS = "--output-format cuffdiff"

The meta.csv I used
file,sample,condition,adapter
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/con1_100k_reads_1.fq.gz,con1,control,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/con1_100k_reads_2.fq.gz,con1,control,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/con2_100k_reads_1.fq.gz,con2,control,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/con2_100k_reads_2.fq.gz,con2,control,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/con3_100k_reads_1.fq.gz,con3,control,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/con3_100k_reads_2.fq.gz,con3,control,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/jev1_100k_reads_1.fq.gz,jev1,JEV,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/jev1_100k_reads_2.fq.gz,jev1,JEV,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/jev2_100k_reads_1.fq.gz,jev2,JEV,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/jev2_100k_reads_2.fq.gz,jev2,JEV,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/jev3_100k_reads_1.fq.gz,jev3,JEV,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa
/data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/cleandata/jev3_100k_reads_2.fq.gz,jev3,JEV,/data5/haozhang/install/CirComPara/tools/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa

I'm not sure if the issue is associated with format of the genome indexes for hisat2, bowtie2 and STAR that I added in vars.py file. It seems the program skip the steps for read mapping in my case running. Could you give an example format how to skip the step for genome indexing that have already generated for the aligners hisat2, bowtie2 and STAR? It can help to save hours for generating genome indexes for each new dataset.

Thank you very much!

Zhuofei

B.T.W I can successfully run circompara with the test dataset in the package. 

B.T.W I'm able to run circompara with my circular RNA-seq data with the genome indexing included in the test run. The step for genome indexing take about five hours.

**Comment by egaffo** [comment]
Dear @qindan2008 and @tigerxu, 

the dependency cycle error was due to a bug when using pre-built indexes. Thank you for reporting. I fixed the issue in the new version [0.1.3](https://github.com/egaffo/CirComPara/releases/tag/v0.1.3). 
Please, update and let me know whether this is working.

Enrico
